config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  mount Sidekiq::Web => '/sidekiq'
  resources :transactions
  resources :users
  get '/rewards' => 'users_rewards#index', as: 'rewards'
  root 'transactions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  has_many :user_rewards, dependent: :destroy
  has_many :users, through: :user_rewards

  # Validation
  validates_presence_of :name

  scope :filter_by_name, ->(reward_name) { find_by('name = ?', reward_name) }
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :user
  after_create :update_loyalty_points

  # Validation
  validates_presence_of :amount, :payment_mode

  DEFAULT_PAYMENTS = ['Cash', 'UPI', 'Credit Card', 'Debit Card'].freeze

  # After create callback to update loyalty points
  def update_loyalty_points
    UpdateLoyaltyPointsJob.perform_now(user.id, id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions, dependent: :destroy
  has_many :user_rewards, dependent: :destroy
  has_many :rewards, through: :user_rewards

  DEFAULT_COUNTRY = 'India'

  # Validation
  validates_presence_of :first_name, :last_name, :country, :date_of_birth, :email

  enum tier: { standard: 0, gold: 1, platinum: 2 }
end

app/models/user_reward.rb
# frozen_string_literal: true

class UserReward < ApplicationRecord
  belongs_to :user
  belongs_to :reward

  enum status: { active: 'active', inactive: 'inactive' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  private

  # Permiting params for signup
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :date_of_birth, :country, :password,
                                 :password_confirmation)
  end

  # Permiting params on updating user
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :country,
                                 :date_of_birth, :password_confirmation, :current_password)
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = current_user.transactions.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = current_user.transactions.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = current_user.transactions.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:amount, :points_generated, :payment_mode)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @user = current_user
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :total_loyalty_points, :date_of_birth, :tier, :country)
  end
end

app/controllers/users_rewards_controller.rb
# frozen_string_literal: true

class UsersRewardsController < ApplicationController
  # GET /rewards
  def index
    @user_rewards = current_user.user_rewards
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark navbar-bg-green">
  <a class="navbar-brand" href="#">Loyalty Program</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="nav navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/transactions">Transactions</a>
      </li>
      <li class="nav-item" r>
        <a class="nav-link" href="/rewards">Rewards</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="nav navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to users_path, class:'nav-link' do %>
          <div title="Profile"><i class="fa fa-user setting-icon" aria-hidden="true"></i></div>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class:'btn action-button' do %>
          <div title="Log Out"><i class="fa fa-sign-out setting-icon" aria-hidden="true"></i></div>
        <% end %>


      <% else %>
        <span class="nav-item"> <%= link_to "Log In", new_user_session_path, class:'nav-link' %></span><%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
      <% end %>
    </ul>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PerxtechTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<div class="login-block">
  <h1>New Transaction</h1>
  <%= form_with(model: transaction) do |form| %>
    <% if transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

        <ul>
          <% transaction.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :amount %>
      <%= form.number_field :amount %>
    </div>

    <div class="field">
      <%= form.label :payment_mode %>
      <%= form.select :payment_mode, Transaction::DEFAULT_PAYMENTS %>
    </div>

    <div class="actions">
      <%= form.submit class: 'submit'%>
    </div>
  <% end %>
</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="head-title">Transactions</h1>
<div class="new_button">
  <%= button_to new_transaction_path, :method => "get", :class => "add_button" do %><span>New Transaction</span><% end %>
</div>
<table class="styled-table table-content-center">
  <thead>
    <tr>
      <th>Id</th>
      <th>Amount</th>
      <th>Points generated</th>
      <th>Payment mode</th>
      <th>Created At</th>
    </tr>
  </thead>

  <tbody>
    <% if @transactions.present? %>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.id %></td>
          <td><%= transaction.amount %></td>
          <td><%= transaction.points_generated %></td>
          <td><%= transaction.payment_mode %></td>
          <td><%= transaction.created_at.strftime('%F') %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan='5' class="test-position"> No Records Found</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transactions/new.html.erb
<%= render 'form', transaction: @transaction %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Points generated:</strong>
  <%= @transaction.points_generated %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @transaction.payment_mode %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/users/_form.html.erb
<div class="login-block">
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div class="field">
      <%= form.label :date_of_birth %>
      <%= form.date_field :date_of_birth, class: "form-control", required: true %>
    </div>

    <div class="field">
      <%= form.label :country %>
      <%= form.select :country, CS.countries.values%>
    </div>

    <div class="actions">
      <%= form.submit class: 'submit' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="head-title">Profile</h1>
<div class="new_button">
  <%= button_to edit_user_path(@user), :method => "get", :class => "add_button" do %><span>Edit User</span><% end %>
</div>
<table class="styled-table">
  <tr><th>First Name <td><%= @user.first_name %></td> </th>
  </tr>
  <tr>
    <th>Last Name<td><%= @user.last_name %></td></th>
  </tr>
  <tr>
    <th>Email <td><%= @user.email %></td></th>
  </tr>
  <tr>
    <th>Total Loyalty Points <td><%= @user.total_loyalty_points %></td></th>
  </tr>
  <tr>
    <th>Loyalty Tier <td><%= @user.tier.titleize %></td></th>
  </tr>
  <tr>
    <th>Date Of Birth <td><%= @user.date_of_birth.strftime('%F') %></td></th>
  </tr>
  <tr>
    <th>Country <td><%= @user.country %></td></th>
  </tr>
</table>

<br>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Total loyalty points:</strong>
  <%= @user.total_loyalty_points %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @user.date_of_birth %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @user.tier %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users_rewards/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="head-title">Rewards</h1>
<table class="styled-table table-content-center">
  <thead>
    <tr>
      <th>Id</th>
      <th>Rewards</th>
      <th>Rewards Created</th>
      <th>Rewards Expiration</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% if @user_rewards.present? %>
      <% @user_rewards.each do |user_reward| %>
        <tr>
          <td><%= user_reward.reward.id %></td>
          <td><%= user_reward.reward.name %></td>
          <td><%= user_reward.created_at.strftime('%F') %></td>
          <td><%= (user_reward.reward.created_at + 1.year).strftime('%F') %></td>
          <td><%= user_reward.status.titleize %></td>
        </tr>
      <% end %>
    <% else %>
    <tr>
      <td colspan='5' class="test-position"> No Records Found</td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>